name: Mirror to GitLab

on:
  push:
    branches:
      - feat/production-automation

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Mirror to GitLab
        run: |
          git remote add gitlab https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_TOKEN }}@gitlab.com/akilapilapitiya/The_Washing_Machine.git
          git push --force gitlab feat/production-automation
